apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: test
spec:
  containers:
    - name: my-container
      image: nginx
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      secret:
        secretName: my-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: test
data:
  config.properties: |
    key1=value1
    key2=value2
