kind: Kustomization
namespace: monitoring
helmCharts:
  - name: prometheus
    releaseName: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 15.4.5
    namespace: monitoring
