kind: Kustomization
namespace: system
helmCharts:
  - name: prometheus
    releaseName: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 25.19.1
    namespace: system
