kind: Kustomization
namespace: system
helmCharts:
  - name: redis
    releaseName: redis
    repo: https://charts.bitnami.com/bitnami
    version: 19.1.2
    namespace: system
    valuesFile: values.yaml
