kind: Kustomization
namespace: system
helmCharts:
  - name: kube-prometheus
    releaseName: kube-prometheus
    repo: https://charts.bitnami.com/bitnami
    version: 8.14.2
    namespace: system
    valuesFile: values.yaml
