service:
  type: NodePort

master:
  replicaCount: 1
  persistence:
    storageClass: "ebs-sc"
    size: 4Gi

data:
  replicaCount: 2
  persistence:
    storageClass: "ebs-sc"
    size: 4Gi

coordinating:
  replicaCount: 0

ingest:
  replicaCount: 0

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true

postgresql:
  enabled: false

externalDatabase:
  host: "postgresql.system.svc.cluster.local"
  port: 5432
  user: admin
  database: test
  password: "password"
