auth:
  adminUser: admin
  adminPassword: "password"

service:
  type: NodePort

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true

postgresql:
  enabled: false

externalDatabase:
  host: "postgresql.system.svc.cluster.local"
  port: 5432
  user: admin
  database: test
  password: "password"
