apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-demonset
  namespace: test
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: busybox:latest
