apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: test
spec:
  template:
    spec:
      containers:
        - name: test-job-container
          image: nginx:latest
          command: ["echo", "Hello, World!"]
      restartPolicy: Never
