apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: test
spec:
  containers:
    - name: my-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
