apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-b-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: test-b
    namespace: default
roleRef:
  kind: ClusterRole
  name: test-b-role
  apiGroup: rbac.authorization.k8s.io
